v158: Correcting PHP warnings and deprecations for paypalwpp ...
zencart/zencart pull request #5060
Opened 2022-07-27 14:04 UTC by lat9

... especially the PPEC button processing.

Fixes #4985
Fixes #5055

2022-07-27 16:57 UTC, lat9 commented
Converted to draft, awaiting review.

2022-08-05 11:26 UTC, lat9 commented
@torvista, waiting for your review to remove the 'Draft' status.

2022-08-05 16:09 UTC, torvista approved these changes
I don't get the null error.
The language selection still does not work for me (shop language as EN still gets PP language as ES), but given the various changes done, probably better to address that as a separate issue.

2022-08-05 16:29 UTC, torvista approved these changes

2022-08-05 17:12 UTC, lat9 commented
> I don't get the null error. The language selection still does not work for me (shop language as EN still gets PP language as ES). I see why, but given the various changes done, probably better to address that as a separate issue.

Thanks for that.  I'll note that the language selection is addressed in #5059

2022-08-14 14:32 UTC, torvista commented
I've had this in use for a week, no issues.

2022-08-29 21:57 UTC, scottcwilson commented
@lat9 Please tag ready for merge when appropriate - I don't want to jump the gun.

2022-09-11 11:35 UTC, brittainmark commented
@lat9  Can this be merged. I need it for #5103.

2022-09-11 15:51 UTC, brittainmark requested changes
I think we have more issues here. Having tried to test this on php 8,2. There are a lot of other warning messages relating to missing array parameters. 

```
[11-Sep-2022 16:43:29 UTC] Request URI: /Test158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/functions/functions_taxes.php(367): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_loworderfee.php(64): zen_get_tax_locations()
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/order_total.php(183): ot_loworderfee->process()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/paypalwpp.php(1753): order_total->pre_confirmation_check()
#4 /home/lotus/public_html/innerlightcrystals/Test158/ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "customer_id" in /home/lotus/public_html/innerlightcrystals/Test158/includes/functions/functions_taxes.php on line 367.

[11-Sep-2022 16:43:29 UTC] Request URI: /Test158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/functions/functions_taxes.php(368): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_loworderfee.php(64): zen_get_tax_locations()
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/order_total.php(183): ot_loworderfee->process()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/paypalwpp.php(1753): order_total->pre_confirmation_check()
#4 /home/lotus/public_html/innerlightcrystals/Test158/ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "sendto" in /home/lotus/public_html/innerlightcrystals/Test158/includes/functions/functions_taxes.php on line 368.

[11-Sep-2022 16:43:29 UTC] Request URI: /Test158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/functions/functions_taxes.php(397): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_loworderfee.php(64): zen_get_tax_locations()
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/order_total.php(183): ot_loworderfee->process()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/paypalwpp.php(1753): order_total->pre_confirmation_check()
#4 /home/lotus/public_html/innerlightcrystals/Test158/ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "entry_zone_id" in /home/lotus/public_html/innerlightcrystals/Test158/includes/functions/functions_taxes.php on line 397.

[11-Sep-2022 16:43:29 UTC] Request URI: /Test158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/functions/functions_taxes.php(398): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_loworderfee.php(64): zen_get_tax_locations()
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/order_total.php(183): ot_loworderfee->process()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/paypalwpp.php(1753): order_total->pre_confirmation_check()
#4 /home/lotus/public_html/innerlightcrystals/Test158/ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "entry_country_id" in /home/lotus/public_html/innerlightcrystals/Test158/includes/functions/functions_taxes.php on line 398.
```

The issue is around tax.
As we do not have an address, we cannot determine how to charge the tax. It could be defaulted to the Store setting as below.

This could be fixed by adding to includes/functions/functions_taxes.php
```
// PapPal processing
// If we're just starting the checkout process via the PPEC button, there's
// no customer or shipping-address currently defined.  Use the store values for tax calculation.
if (!zen_is_logged_in())  {
    $tax_address['zone_id'] = (int)STORE_COUNTRY;
    $tax_address['country_id'] = (int)STORE_ZONE;
    return $tax_address;
}
```
after line 358
```
    $tax_address = [];

```

2022-09-11 16:14 UTC, brittainmark commented
Additional more logfile warnings for each part of ordertotal when customer is not logged in! Occur when you click the pay by paypal button for quick checkout.
```
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php(147): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php(92): ot_group_pricing->calculate_deductions()
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/order_total.php(183): ot_group_pricing->process()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/paypalwpp.php(1753): order_total->pre_confirmation_check()
#4 /home/lotus/public_html/innerlightcrystals/Test158/ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "customer_id" in /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php on line 147.

[11-Sep-2022 16:06:37 UTC] Request URI: /Test158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php(148): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php(92): ot_group_pricing->calculate_deductions()
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/order_total.php(183): ot_group_pricing->process()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/paypalwpp.php(1753): order_total->pre_confirmation_check()
#4 /home/lotus/public_html/innerlightcrystals/Test158/ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "customers_group_pricing" in /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php on line 148.

[11-Sep-2022 16:06:37 UTC] Request URI: /Test158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php(150): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php(92): ot_group_pricing->calculate_deductions()
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/order_total.php(183): ot_group_pricing->process()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/paypalwpp.php(1753): order_total->pre_confirmation_check()
#4 /home/lotus/public_html/innerlightcrystals/Test158/ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "customers_group_pricing" in /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php on line 150.

[11-Sep-2022 16:06:37 UTC] Request URI: /Test158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php(152): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php(92): ot_group_pricing->calculate_deductions()
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/order_total.php(183): ot_group_pricing->process()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/paypalwpp.php(1753): order_total->pre_confirmation_check()
#4 /home/lotus/public_html/innerlightcrystals/Test158/ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "group_percentage" in /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php on line 152.

[11-Sep-2022 16:06:37 UTC] Request URI: /Test158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php(147): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php(92): ot_group_pricing->calculate_deductions()
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/order_total.php(67): ot_group_pricing->process()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/paypalwpp.php(1754): order_total->process()
#4 /home/lotus/public_html/innerlightcrystals/Test158/ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "customer_id" in /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php on line 147.

[11-Sep-2022 16:06:37 UTC] Request URI: /Test158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php(148): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php(92): ot_group_pricing->calculate_deductions()
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/order_total.php(67): ot_group_pricing->process()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/paypalwpp.php(1754): order_total->process()
#4 /home/lotus/public_html/innerlightcrystals/Test158/ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "customers_group_pricing" in /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php on line 148.

[11-Sep-2022 16:06:37 UTC] Request URI: /Test158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php(150): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php(92): ot_group_pricing->calculate_deductions()
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/order_total.php(67): ot_group_pricing->process()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/paypalwpp.php(1754): order_total->process()
#4 /home/lotus/public_html/innerlightcrystals/Test158/ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "customers_group_pricing" in /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php on line 150.

[11-Sep-2022 16:06:37 UTC] Request URI: /Test158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php(152): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/order_total/ot_group_pricing.php(92): ot_group_pricing->calculate_deductions()
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/order_total.php(67): ot_group_pricing->process()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/paypalwpp.php(1754): order_total->process()
```
i'm looking for options.

2022-09-11 16:40 UTC, brittainmark commented
I think I also have a solution to my previous issue.
Change line 49 in include>modules\order_total\ot_gv.php from
`if (IS_ADMIN_FLAG !== true) {`
to
`if (IS_ADMIN_FLAG !== true && zen_is_logged_in()) {`

and add to include>modules\order_total\ot_group_pricing.php 
about line 30
```
if (!zen_is_logged_in()) {
        return;
    }
```

thus
```
function process() {
    global $order, $currencies, $db;
    if (!zen_is_logged_in()) {
        return;
    }
```

Neither are valid if you are not logged in so should not effect anything else.

2022-09-13 14:47 UTC, brittainmark commented
I assume you will mod this pr.

2022-09-13 14:51 UTC, brittainmark commented
Are you going to mod functions_taxes as well?

2022-09-16 10:18 UTC, scottcwilson commented
@lat9 Please mark when this PR ready for merge.

2022-09-20 10:25 UTC, torvista commented
In my local testing using this PR.
1) errors 
due to the use of undefined $response['L_ERRORCODE0']
due to the use of undefined $response[$this->infoPrefix . 'FEEAMT']
Sent info directly to lat9 as included customer logs and my version of this file is heavily modified with ceon payment surcharge.

2) error due to use of undefined $response['L_LONGMESSAGE2']
which could be handled/set in the same place as the above solution.

3) error due to use of undefined  $_SESSION['paypal_ec_token'] in this log call
    $this->zcLog('termEC-2', 'BEFORE: $this->showPaymentPage = ' . (int)$this->showPaymentPage . "\nToken Data:" . $_SESSION['paypal_ec_token']);
as it may have been unset a few lines previous.

4) and for php 8.2, this works ($form_action_url must be public)
    protected $_check, $buttonSourceDP, $cards, $cc_type_check, $codeTitle, $codeVersion, $doDPonly, $enableDirectPayment, $emailAlerts, $new_acct_notify;
    public $form_action_url;

2022-09-20 15:47 UTC, brittainmark commented
I am having another strange problem.
If I put an item in the cart then click express checkout. I am taken to the paypal page. 
I complete the paypal page, and I am returned to the checkout_payment not the checkout_shipping page as I would expect.
If I complete the checkout_paymant page I am then sent to the checkout_shipping page.
The process then follows the normal route through checkout_payment then checkout_confirmation etc.

I cannot work out why this is happening.

2022-10-06 17:15 UTC, brittainmark commented
Finally, found the little bugger.
The issue is that includes\modules\payment\paypalwpp,php resets the shopping basket to check if any items have been combined with a previous login's not purchased basket. This resets the $_SESSION['cartID'] to blank. Need to change paypalwpp on @lat9  version lines  2827-2845 on Main zencart lines 2779-2846
```
        // bof: not require part of contents merge notice
        // restore cart contents
        $_SESSION['cart']->restore_contents();
        // eof: not require part of contents merge notice

        // check current cart contents count if required
        if (SHOW_SHOPPING_CART_COMBINED > 0 && $zc_check_basket_before > 0) {
          $zc_check_basket_after = $_SESSION['cart']->count_contents();
          if (($zc_check_basket_before != $zc_check_basket_after) && $_SESSION['cart']->count_contents() > 0 && SHOW_SHOPPING_CART_COMBINED > 0) {
            if (SHOW_SHOPPING_CART_COMBINED == 2) {
              // warning only do not send to cart
              $messageStack->add_session('header', WARNING_SHOPPING_CART_COMBINED, 'caution');
            }
            if (SHOW_SHOPPING_CART_COMBINED == 1) {
              // show warning and send to shopping cart for review
              $messageStack->add_session('shopping_cart', WARNING_SHOPPING_CART_COMBINED, 'caution');
              zen_redirect(zen_href_link(FILENAME_SHOPPING_CART, '', 'NONSSL'));
            }
          }
        }
```
to 
```
             // bof: not require part of contents merge notice
            // restore cart contents
            $_SESSION['cart']->restore_contents();
            // eof: not require part of contents merge notice
            $zc_check_basket_after = $_SESSION['cart']->count_contents();
            if ($zc_check_basket_before > 0 && $zc_check_basket_before == $zc_check_basket_after) {
                //  If contents still same set the cartID
                $_SESSION['cartID'] = $_SESSION['cart']->cartID;
            }
            // check current cart contents count if required
            if (SHOW_SHOPPING_CART_COMBINED > 0 && $zc_check_basket_before > 0) {
                $zc_check_basket_after = $_SESSION['cart']->count_contents();
                if (($zc_check_basket_before != $zc_check_basket_after) && $_SESSION['cart']->count_contents() > 0 && SHOW_SHOPPING_CART_COMBINED > 0) {
                    if (SHOW_SHOPPING_CART_COMBINED == 2) {
                        // warning only do not send to cart
                        $messageStack->add_session('header', WARNING_SHOPPING_CART_COMBINED, 'caution');
                    }
                    if (SHOW_SHOPPING_CART_COMBINED == 1) {
                        // show warning and send to shopping cart for review
                        $messageStack->add_session('shopping_cart', WARNING_SHOPPING_CART_COMBINED, 'caution');
                        zen_redirect(zen_href_link(FILENAME_SHOPPING_CART, '', 'NONSSL'));
                    }
                } 
            }
```

2022-10-07 05:16 UTC, brittainmark commented
@scottcwilson do you want me to change main zen cart as I do not believe issue above is related to @lat9 changes.
Or does that just make it messy?

2022-10-07 09:34 UTC, scottcwilson commented
Please go ahead and make your changes independently in your own PR. Trying to get things wrapped up.

2022-10-07 11:41 UTC, brittainmark commented
@scottcwilson You will still need this to be completed. As it fixes a lot of other errors/warnings.

2022-10-08 14:15 UTC, merged