Regaining Titles for Listing Pages
zencart/zencart pull request #5215
Opened 2022-09-13 21:39 UTC by dbltoe

Somehow, in the midst of my ineptitude with GitHub, these changes got dropped. Unfortunately, I did not notice until I checked Lighthouse after upgrading my test site with all the latest files

2022-09-13 22:10 UTC, proseLA commented
do not modify anything in the header/stamp area.  

there is no alpha2 release.  

anyone can look at the blame and see the history of the file.

stamping the header portion of the file is an automated process the maintainers do prior to a new release.

2022-09-14 00:05 UTC, dbltoe commented
Wasn't blaming, just trying to establish a reference point and if alpha2 was good enough for lat9 in https://github.com/zencart/zencart/pull/5215/files#diff-067db5f9774804c3d45e98afb801c86c757dcac328b8d14ddc8766188586090d, I figured I would go with that.

2022-09-14 00:48 UTC, proseLA commented
not sure what you are talking about.

when looking at a file, there is a button called blame on the top right:

![image](https://user-images.githubusercontent.com/1095136/190033072-e16aef24-8692-41f1-9fa3-3cdb987a345b.png)

if you were to click on that button, you can then see the history of the file including who modified any particular line:

https://github.com/zencart/zencart/blame/v158/includes/modules/featured_products.php

the stamp that you see at the top is done prior to a release by an automated program written by zcwilt.  you can see the commit for the stamp prior to the alpha release here:

https://github.com/zencart/zencart/commit/532a5904f0bab3f69c9a3703f7bc3593a54894a9

apparently the alpha2 release was done 15 days ago.  see:

https://github.com/zencart/zencart/tags

the stamp was done here:

https://github.com/zencart/zencart/commit/b33bf3888b0f7b660d0f7747c5901ff968eca5ab

i stand by my comments of not modifying that header information.  the alpha2 release was 15 days ago.

you modifying that header information implies that file was part of that release.  it was not.

2022-09-15 17:29 UTC, zcwilt commented
@proseLA brings up a good point

Should someone making a commit update the header code.

There's no reason not to, if you understand the format, then updating reduces the amount of work the automated process has to do.

However unless you do it correctly, you are just wasting your time as it will eventually be overwritten.

I've always thought we need a conversation around what we put in the headers. something for another day.

2022-09-15 17:38 UTC, dbltoe commented
Pointing out ways to accomplish a goal are always better than just pointing out errors.
I look forward to instructional information.

2022-09-15 17:55 UTC, scottcwilson commented
This thread is quite confusing (at least to me) - so just to be sure anyone reading understands how the header blocks work:

This block at the top of each file: 

```
 * @copyright Copyright 2003-2022 Zen Cart Development Team
 * @copyright Portions Copyright 2003 osCommerce
 * @license http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
 * @version $Id: torvista 2022 Feb 18 Modified in v1.5.8-alpha $
```

does not need to be hand-edited as long as it is present.  It gets updated when we do a release. 

If you're building a new file, then please add it (and it will get updated in the next release).

2022-09-15 18:05 UTC, zcwilt commented
https://github.com/zencart/zencart/discussions/5216

2022-09-16 10:07 UTC, scottcwilson commented
Why are we hardcoding strings like "Main Store Logo" and "Product ID"?

2022-09-16 10:08 UTC, scottcwilson requested changes

2022-09-16 10:08 UTC, scottcwilson commented on includes/modules/featured_products.php
> +    'text' => (($featured_products->fields['products_image'] == '' and PRODUCTS_IMAGE_NO_IMAGE_STATUS == 0) ? '' : '<a href="' . zen_href_link(zen_get_info_page($featured_products->fields['products_i
Let's not hardcode English language strings.

2022-11-06 10:37 UTC, scottcwilson commented
Closing this PR which is now a mix of various things.  Let's built smaller PRs so we can get them processed more easily.

2022-11-06 10:37 UTC, closed without merging