Add test for null
zencart/zencart pull request #5375
Opened 2022-11-06 10:04 UTC by brittainmark

Have added tests for null value in a few places to avoid depreciation errors in php8.2. An alternative is to place (string) before the parameter. e.g.
`strlen((string)$string)`

This also removes the depreciation warning. If you think this is a better approach, let me know and I'll redo.

2022-11-06 10:26 UTC, brittainmark commented
For info, just ran this test
```php
<?php
$mark = null;
$str = (string)$mark;
if (is_null($str)) echo "<br>is_null";  // not true
if ($str === null) echo "<br>===Null";  // not true
if ($str == null) echo "<br>==Null";
if ($str === '') echo "<br>===''";
if ($str ==' ') echo "<br>==''";

```
returns
==Null
===''
==''

2022-11-06 13:29 UTC, lat9 commented
I'm finding that last one very interesting.  What version of PHP are you running to get that, essentially, `'' == ' '`?

2022-11-06 13:34 UTC, brittainmark commented
Sorry, that was a typo. Should have been `if ($str == '') echo "<br>==''";` otherwise it would have been very interesting. It was run on php 8.2RC5

2022-11-06 13:40 UTC, lat9 commented
Whew, I was heading to make another pot of coffee trying to wrap my head around that!

For the three functions being corrected, would you please simply cast the presumed-to-be-string input to a `(string)` on entry?  I think it makes the code more readable.

2022-11-06 15:09 UTC, brittainmark commented
zen_trunc_string needs two (string) as it possible to reach line 120 `if (strlen((string)$str) <= $len) return $str;`
I have not placed any further down in the function, as you'd need to enter -ve $len to reach any further down the function.

2022-11-11 19:20 UTC, lat9 requested changes
I'm liking the approach that @proseLA took with the quick-return; please update.

2022-11-12 17:56 UTC, brittainmark commented
Have recoded to follow @proseLA method and do quick return of empty string if null submitted.

2022-11-13 12:45 UTC, lat9 approved these changes

2022-11-13 12:45 UTC, merged