Change " />" in root, zc_install, and Admin root.
zencart/zencart pull request #5384
Opened 2022-11-10 17:54 UTC by dbltoe

Changes " />" to "/>" and "<br/>" to "<br>" in the above folders.

This leaves just a few files that need to be checked by someone more familiar with the format.

2022-11-10 22:10 UTC, torvista commented on admin/mail.php
> +              $message_preview = str_replace(array('<br>', '<br>'), "<br>\n", $message_preview);
I don't think this change is correct

2022-11-12 11:42 UTC, scottcwilson commented on admin/mail.php
> +              $message_preview = str_replace(array('<br>', '<br>'), "<br>\n", $message_preview);
I agree with @torvista

2022-11-12 11:43 UTC, scottcwilson requested changes
See note from @torvista

2022-11-12 16:23 UTC, dbltoe commented
I agree but, as usual, changing the file back has resulted only in creating a new commit that sits with another commit and doesn't want to be sent to zencart/zencart without taking everything with it in a new PR.

There is absolutely no match in the GitHub docs for making a change to a file that has been committed.  At least, none that I can find.

2022-11-12 17:33 UTC, scottcwilson commented
Please don't modify 
zc_install/includes/systemChecks.yml
and don't change SHOW_SHOPPING_CART_BOX_STATUS and DEFINE_BREADCRUMB_STATUS in the .sql files or you'll break upgrades. 

It's probably better if you only change things in includes/ - everything 
else has a million pitfalls. Changing the .sql scripts and zc_install 
in particular are fraught. 

For your question
> There is absolutely no match in the GitHub docs for making a change to a file that has been committed. 

you should be able to check out the branch in question, modify the file, and do 

```
git add <file>
git commit --amend
git push --force
```

2022-11-26 03:12 UTC, proseLA commented
please do not merge.  please.

2022-11-26 11:13 UTC, scottcwilson commented
Agreed.

2022-11-26 11:13 UTC, closed without merging