Optionally Bypass loading substring-matching language files
zencart/zencart pull request #5397
Opened 2022-11-20 16:58 UTC by scottcwilson

This worked before PHP 8 because additional duplicate defines were simply dropped.  Now they create log files, so we have to provide a mechanism to disallow (at least for legacy language files) if it will be harmful. 

I don't think the same change is required for includes/classes/ResourceLoaders/CatalogArraysLanguageLoader.php because there, the first setting wins and there's no PHP warning.

2022-11-20 18:29 UTC, scottcwilson commented
Documentation: https://docs.zen-cart.com/dev/code/158_order_language_files/#substring-matching

2022-11-21 08:52 UTC, lat9 requested changes
Great idea, since the `account`, `account_history` and `account_history_info` language files all get loaded on the `account` page (and have for ages)!  This can prevent some head-scratching conditions.

2022-11-21 08:52 UTC, lat9 commented on includes/classes/ResourceLoaders/CatalogFilesLanguageLoader.php
> +        }
Let's simplify this a bit:
```php
if (defined('NO_LANGUAGE_SUBSTRING_MATCH') && in_array($this->currentPage, NO_LANGUAGE_SUBSTRING_MATCH)) {
    $files_to_match = $this->currentPage;
} else {
    $files_to_match = $this->currentPage . '(.*)';
}
$files = $this->fileSystem->listFilesFromDirectoryAlphaSorted($directory, '~^' . $files_to_match  . '\.php$~i');
```

2022-11-21 08:52 UTC, lat9 commented on includes/classes/ResourceLoaders/CatalogFilesLanguageLoader.php
> +        }
... and then simplify this as well
```php
$files = $this->fileSystem->listFilesFromDirectoryAlphaSorted($directory, '~^' . $files_to_match  . '\.php$~i');
```

2022-11-21 10:59 UTC, scottcwilson commented on includes/classes/ResourceLoaders/CatalogFilesLanguageLoader.php
> +        }
done

2022-11-21 11:39 UTC, lat9 approved these changes

2022-11-21 11:39 UTC, merged