Add old signatures for backwards compatibility
zencart/zencart pull request #5439
Opened 2022-12-03 11:49 UTC by scottcwilson

These function signatures were changed in 1.5.8; let's add back the old signatures so that plugins won't break.  We can add a deprecated log in the future.

2022-12-03 11:56 UTC, scottcwilson commented
@lat9 Please merge asap.

Note to self: need to update working copy of release specific upgrade considerations, update 158 Known Bugs once this is finalized.

2022-12-03 12:32 UTC, torvista commented
https://docs.zen-cart.com/user/upgrading/release_specific_upgrade_considerations/

2022-12-03 13:39 UTC, lat9 requested changes
For each, let's not defer the creation of the deprecated log.  Otherwise, it'll just take more time for plugins to "catch up".

2022-12-03 16:26 UTC, scottcwilson commented
@torvista The changes were not documented.  But even documenting them would not be sufficient; there's no need to break things unless you have literally no choice.

2022-12-03 17:35 UTC, lat9 approved these changes

2022-12-03 17:35 UTC, merged

2022-12-03 17:53 UTC, torvista commented
>there's no need to break things unless you have literally no choice.

If it is decided that similar functions should be culled and replaced with something more efficient, that's progress.
But yes the deprecated functions should have remained temporarily with warnings.
And as long as that is documented, I don't see how upgraders can complain. If people are upset about change, why do they upgrade?

2023-02-09 17:28 UTC, scottcwilson commented
For search: 
Old name: zen_draw_products_pull_down
New Name: zen_draw_pulldown_products