Update functions_dates.php
zencart/zencart pull request #5618
Opened 2023-02-22 14:13 UTC by brittainmark

Remove need to edit zen_date_raw function if changing to UK date format.

2023-02-23 08:04 UTC, brittainmark commented
Added as requested and squashed.

2023-02-27 17:10 UTC, lat9 requested changes

2023-02-27 17:10 UTC, lat9 commented on includes/functions/functions_dates.php
> +     * $date should be in format mm/dd/yyyy or dd/mm/yy
`dd/mm/yy` should be `dd/mm/yyyy`

2023-02-27 21:09 UTC, lat9 approved these changes

2023-02-27 21:09 UTC, merged