show/hide images on the admin catalog/product page
zencart/zencart pull request #5994
Opened 2023-09-14 23:15 UTC by proseLA

fixes #5993

2023-09-15 00:40 UTC, scottcwilson commented
Not sure a toggle is really needed; I thought this was just going to be another flag.

2023-09-15 02:43 UTC, lat9 commented
> Not sure a toggle is really needed; I thought this was just going to be another flag.

Per the @torvista comment in the associated issue, I believe that having a toggle (so that an admin has control of their environment) is a good thing.

2023-09-15 02:52 UTC, lat9 commented
@proseLA, what do you think the effort would be to make this a session-based setting for the admin.  That way, once they've chosen to see/not see the images the selection would be remembered for their current login.

2023-09-15 07:01 UTC, torvista commented
This modification still downloads the images and but then offers the option to hide them.
So it saves screen space, offers a more compact listing, but does not have a speed advantage.

I think the most complete implementation of this would be to prevent images being downloaded and be session-maintained.
That's what I did.

2023-09-15 11:17 UTC, scottcwilson commented
> > Not sure a toggle is really needed; I thought this was just going to be another flag.
> 
> Per the @torvista comment in the associated issue, I believe that having a toggle (so that an admin has control of their environment) is a good thing.

Literally nothing else in the project works this way, but Steve has yet another personal preference, and he has unlimited time and energy for complaining, so we'll do it his way?  

This doesn't seem like a great process.  But it's not important enough to me to fight over, so do what you think is best.

2023-09-15 12:26 UTC, torvista commented
>he has unlimited time and energy for complaining
I'll bypass the fundamental rule of not replying when angry.

Scott, you have an unlimited ability to repeatedly insult people. You just don't learn.
Where is my complaint in this thread?
I don't complain, I contribute. Or rather I did.

2023-09-15 22:39 UTC, proseLA commented
@torvista i am no longer a fan of page reloads.  i think modern website design is more about sending all of the data down to the browser, and then using css and javascript/jquery to style the data as needed for the page.  i think all of these image files should be reasonably small, and in addition, browser caching of image files means you are not continuously reloading these image files.  again, my opinion is that the speed savings by not downloading the image files are minimal (but i have not seen your image files), but feel free to prove me wrong.  i know in my experience, other shopping cart software's admin experience is far slower than zc.  

@scottcwilson i did not code this to steve's preference.  i coded it to what made sense to me.  in addition, i think the rationale that nothing else is done this way is not a good rationale.  either we want zc to move forward with new ideas, incorporating more modern ideas of web design, or we do not.  personally i am more a fan of the former.

2023-09-16 02:13 UTC, lat9 requested changes
A couple of nit-picks, as usual.

2023-09-16 02:13 UTC, lat9 commented on admin/category_product_listing.php
> +                    <td><input type="button" id="imageView" class="btn btn-info btn-xs" value="<?= $buttonText; ?>"/>
For an HTML5 input, there's no `/` at the end-of-tag.

2023-09-16 02:13 UTC, lat9 commented on admin/category_product_listing.php
> +            $('#imageView').click(function () {
Use `$('#imageView').on('click', function() {`

2023-09-16 02:13 UTC, lat9 commented on includes/classes/ajax/zcAjaxAdminSessionChange.php
> +
Remove unneeded empty lines, please.

2023-09-16 12:24 UTC, lat9 approved these changes

2023-09-16 12:24 UTC, merged