OT modules calculation correction
zencart/zencart pull request #6392
Opened 2024-04-11 08:28 UTC by piloujp

Mainly rewrite of ot_coupon.php to be consistent with other modules and different options settings.
Bug corrections on ot_gv and ot_group_pricing.
See forum thread '[Discount coupon value](https://www.zen-cart.com/showthread.php?230003-Discount-coupon-value/page3)'.
Related to #6339

2024-04-14 20:18 UTC, drbyte commented
Sorry to be nitpicky, but your text editor is using tabs instead of spaces for indentation, and thus the alignment of the code is way off all over this PR.

One example:
![Screen Shot 2024-04-14 at 4 16 07 PM](https://github.com/zencart/zencart/assets/404472/9300383b-d53f-4202-9352-21e147b2f02b)

2024-04-15 05:35 UTC, piloujp commented
Sorry for that, I will try to change that. It is the automatic indentation, I think. Until I set that, I will use a regex to fix that and submit new commits.

2024-04-16 13:30 UTC, lat9 commented on includes/modules/order_total/ot_coupon.php
> +                            $od_amount['total'] = (DISPLAY_PRICE_WITH_TAX == 'true' ? $orderAmountTotal - $orderTotalDetails['orderTax'] : $orderAmountTotal) * $coupon_details['coupon_amount'] / 100;
Here, and in other places, check for `DISPLAY_PRICE_WITH_TAX === 'true'`.

2024-04-16 15:57 UTC, lat9 requested changes
See associated comment

2024-04-26 08:46 UTC, piloujp commented
After recently working on multiple tax rates calculation, I realized that files in this PR need more modification and these modifications can't be treated independently of my more recent code updates. I am not sure what is best, make a new PR or updating this one. I try to separate problems (and PRs) as much as possible, but It is not going to work in this case.

2024-05-05 15:39 UTC, piloujp commented
Closing this PR replaced by PR #6432 .

2024-05-05 15:41 UTC, closed without merging