Update collect_info.php fixed image size
zencart/zencart pull request #6795
Opened 2024-10-03 02:18 UTC by shot-guun

Fixed product image size stops big images when editing product

2024-10-03 16:00 UTC, barco57 commented
I don't particularly like that declaring both small height and width messes with proportion of the displayed image. declaring just width works for me but I used MEDIUM_IMAGE_WIDTH so it displayed at the same size as it is going to be displayed on the front end product page

2024-10-03 16:48 UTC, shot-guun commented
I see what you mean. I use a carousel on products page which shows small images until clicked but I do agree with keeping proportions, thanks.

2025-01-06 20:54 UTC, scottcwilson commented
@shot-guun Would you please attach images showing before and after your change for documentation?  Thank you and thanks for doing this.

2025-01-08 02:29 UTC, drbyte commented
Something to keep in mind:
- the "main" product image is also the one used for the thumbnail, even if the image itself is higher resolution
- the "small" dimensions are the thumbnail size, and are best applied to the "main"/thumbnail image
- if using MEDIUM, then you "could" still display the "main" image, but you'd be scaling it up to medium dimensions, unless you also tell it to render the _MED image.
- and for LARGE, the same scenario if you don't render the _LRG image.

Summary: if you've actually optimized your images for proper display at each resolution, then scaling up the main image to "medium" is likely gonna look a bit grainy.

Isn't the "real" problem that you're getting bizarre image sizes "because" you've not actually created images for each resolution in the first place?

2025-01-08 04:52 UTC, barco57 commented
"Isn't the "real" problem that you're getting bizarre image sizes "because" you've not actually created images for each resolution in the first place?" - who does this anymore? I haven't seen it in years.... image handler does the image resizing.

2025-01-08 09:10 UTC, torvista commented
> you've not actually created images for each resolution in the first place?" - **who does this anymore**?

Good question. 

https://github.com/zencart/zencart/discussions/6380

2025-02-02 23:20 UTC, drbyte commented on admin/includes/modules/collect_info.php
> +                <?php echo zen_info_image($pInfo->products_image, (is_array($pInfo->products_name) ? $pInfo->products_name[$_SESSION['languages_id']] : $pInfo->products_name),SMALL_IMAGE_WIDTH,SMALL_
```suggestion
                <?php echo zen_info_image($pInfo->products_image, (is_array($pInfo->products_name) ? $pInfo->products_name[$_SESSION['languages_id']] : $pInfo->products_name), MEDIUM_IMAGE_WIDTH); ?>
```

2025-02-02 23:23 UTC, drbyte requested changes
Let's go with medium.

2025-02-07 21:12 UTC, drbyte commented
I can't edit the PR or contribute to it due to blocks set against it in your branch. 
I'll just merge and edit it afterward.

2025-02-07 21:12 UTC, merged